use argon2::password_hash::{SaltString, rand_core::OsRng};
use argon2::{Argon2, PasswordHash, PasswordHasher, PasswordVerifier};
use bcrypt::verify as verify_bcrypt;
use sqlx::PgPool;
use uuid::Uuid;

pub struct AdminUser {
    #[allow(dead_code)]
    pub id: Uuid,
    pub email: String,
}

struct UserRow {
    id: Uuid,
    password_hash: String,
    is_active: bool,
}

pub async fn find_and_verify(pool: &PgPool, email: &str, password: &str) -> Option<AdminUser> {
    let row = sqlx::query_as::<_, (Uuid, String, bool)>(
        "SELECT id, password_hash, is_active FROM admin_users WHERE email = $1",
    )
    .bind(email)
    .fetch_optional(pool)
    .await
    .ok()
    .flatten()
    .map(|(id, password_hash, is_active)| UserRow {
        id,
        password_hash,
        is_active,
    })?;

    if !row.is_active {
        return None;
    }

    if !verify_password_hash(&row.password_hash, password) {
        return None;
    }

    Some(AdminUser {
        id: row.id,
        email: email.to_string(),
    })
}

fn verify_password_hash(stored_hash: &str, password: &str) -> bool {
    // Argon2 hashes generated by this service use PHC string format.
    if stored_hash.starts_with("$argon2") {
        if let Ok(parsed) = PasswordHash::new(stored_hash) {
            return Argon2::default()
                .verify_password(password.as_bytes(), &parsed)
                .is_ok();
        }
        return false;
    }

    // Legacy seed data uses bcrypt ($2a/$2b/$2y). Support it for local/dev compatibility.
    if stored_hash.starts_with("$2a$") || stored_hash.starts_with("$2b$") || stored_hash.starts_with("$2y$") {
        return verify_bcrypt(password, stored_hash).unwrap_or(false);
    }

    false
}

/// Minimum password requirements for admin accounts.
pub fn validate_password_strength(password: &str) -> Result<(), &'static str> {
    if password.len() < 12 {
        return Err("password must be at least 12 characters");
    }
    if !password.chars().any(|c| c.is_ascii_uppercase()) {
        return Err("password must contain an uppercase letter");
    }
    if !password.chars().any(|c| c.is_ascii_lowercase()) {
        return Err("password must contain a lowercase letter");
    }
    if !password.chars().any(|c| c.is_ascii_digit()) {
        return Err("password must contain a digit");
    }
    Ok(())
}

pub fn hash_password(password: &str) -> String {
    let salt = SaltString::generate(&mut OsRng);
    Argon2::default()
        .hash_password(password.as_bytes(), &salt)
        .expect("Argon2 hashing is infallible for valid salt")
        .to_string()
}

/// On startup, sync the bootstrap admin account from env vars.
///
/// - If `HALTCHAIN_BOOTSTRAP_ADMIN_EMAIL` + `HALTCHAIN_BOOTSTRAP_ADMIN_PASSWORD` are set,
///   the account is created-or-updated (upsert) so the env vars are always the source of truth.
/// - If the env vars are absent AND admin_users is empty, a warning is logged.
pub async fn bootstrap_if_empty(pool: &PgPool) {
    let email = std::env::var("HALTCHAIN_BOOTSTRAP_ADMIN_EMAIL").ok();
    let password = std::env::var("HALTCHAIN_BOOTSTRAP_ADMIN_PASSWORD").ok();

    match (email, password) {
        (Some(email), Some(password)) => {
            if let Err(reason) = validate_password_strength(&password) {
                tracing::warn!(email = %email, reason, "bootstrap admin password is weak");
            }
            let hash = hash_password(&password);
            let result = sqlx::query(
                "INSERT INTO admin_users (email, password_hash, is_active) VALUES ($1, $2, true)
                 ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash, is_active = true",
            )
            .bind(&email)
            .bind(&hash)
            .execute(pool)
            .await;
            match result {
                Ok(_) => tracing::info!(email = %email, "bootstrap admin account synced"),
                Err(e) => tracing::error!("failed to sync bootstrap admin user: {e}"),
            }
        }
        _ => {
            let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM admin_users")
                .fetch_one(pool)
                .await
                .unwrap_or(0);
            if count == 0 {
                tracing::warn!(
                    "no admin users exist — set HALTCHAIN_BOOTSTRAP_ADMIN_EMAIL and \
                     HALTCHAIN_BOOTSTRAP_ADMIN_PASSWORD to create the first account"
                );
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use bcrypt::hash as hash_bcrypt;

    use super::{hash_password, verify_password_hash};

    #[test]
    fn verifies_argon2_password_hash() {
        let hash = hash_password("admin123");
        assert!(verify_password_hash(&hash, "admin123"));
        assert!(!verify_password_hash(&hash, "wrong"));
    }

    #[test]
    fn verifies_legacy_bcrypt_password_hash() {
        let bcrypt_hash = hash_bcrypt("admin123", 12).expect("bcrypt hash failed");
        assert!(verify_password_hash(&bcrypt_hash, "admin123"));
        assert!(!verify_password_hash(&bcrypt_hash, "wrong"));
    }
}
