apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "haltchain-operator.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "haltchain-operator.labels" . | nindent 4 }}
{{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
