{{- if .Values.webhook.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webhook.tls.secretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "haltchain-operator.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- if and .Values.webhook.tls.cert .Values.webhook.tls.key }}
  tls.crt: {{ .Values.webhook.tls.cert | b64enc }}
  tls.key: {{ .Values.webhook.tls.key | b64enc }}
  {{- else }}
  tls.crt: ""
  tls.key: ""
  {{- end }}
{{- end }}
